### ISSUE TITLE
Trying the flag-status API

### ISSUE THREAD

**Issue by grroschel** [sabbatiw/flag-status#1]
I'm new to Python/Pandas, etc., and I'm attempting to use your flag status API. When I do a pd.read_html(your_url) or a json read of your url I receive the following error message:

<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'lab.seekup.nl'. (_ssl.c:1045)>

Can you provide me with a sample of how to access the API or tell me what I'm doing wrong?

**Comment by sabbatiw** [comment]
grroschel,

Apologies, please use https://bluepale.net/flag-status/.
